const GROUND_FLOOR_BLUEPRINT = require("../assets/maps/GroundFloor2.jpg");
const MEZZANINE_BLUEPRINT = require("../assets/maps/Mezzanine2.jpg");
const SECOND_FLOOR_BLUEPRINT = require("../assets/maps/SecondFloor2.jpg");
const THIRD_FLOOR_BLUEPRINT = require("../assets/maps/ThirdFloor2.jpg");

export const MONITORING_MAP_FLOORS = [
  { id: "ground", name: "Ground Floor", icon: "home-outline" },
  { id: "first", name: "Mezzanine", icon: "arrow-up-outline" },
  { id: "second", name: "Second Floor", icon: "layers-outline" },
  { id: "third", name: "Third Floor", icon: "layers-outline" },
];

export const MONITORING_MAP_OFFICES = [
  { id: "ground-lobby", name: "Lobby", floor: "ground", icon: "home-outline" },
  { id: "ground-cashier", name: "Cashier", floor: "ground", icon: "cash-outline" },
  { id: "ground-staff", name: "Staff", floor: "ground", icon: "people-outline" },
  { id: "ground-accounting", name: "Accounting", floor: "ground", icon: "calculator-outline" },
  { id: "ground-registrar", name: "Registrar", floor: "ground", icon: "document-text-outline" },
  { id: "ground-file-room", name: "File Room", floor: "ground", icon: "folder-open-outline" },
  { id: "ground-storage-main", name: "Storage", floor: "ground", icon: "archive-outline" },
  { id: "ground-storage-small", name: "Storage Room", floor: "ground", icon: "cube-outline" },
  { id: "ground-offices", name: "Offices", floor: "ground", icon: "business-outline" },
  { id: "ground-pwd-cr", name: "PWD CR", floor: "ground", icon: "accessibility-outline" },
  { id: "ground-he-she", name: "H.E/SHE", floor: "ground", icon: "medical-outline" },
  { id: "ground-kitchen", name: "Kitchen", floor: "ground", icon: "restaurant-outline" },
  { id: "ground-fire-exit", name: "Fire Exit", floor: "ground", icon: "exit-outline" },
  { id: "conference-room", name: "Conference Room", floor: "first", icon: "people-outline" },
  { id: "chairman", name: "Chairman", floor: "first", icon: "person-circle-outline" },
  { id: "flight-operations", name: "Flight Operations", floor: "first", icon: "airplane-outline" },
  { id: "head-of-training-room", name: "Head Of Training Room", floor: "first", icon: "school-outline" },
  { id: "it-room", name: "I.T Room", floor: "first", icon: "desktop-outline" },
  { id: "faculty-room", name: "Faculty Room", floor: "first", icon: "people-circle-outline" },
  { id: "academy-director", name: "Academy Director", floor: "first", icon: "briefcase-outline" },
  { id: "mezzanine-cr", name: "CR", floor: "first", icon: "water-outline" },
  { id: "sto", name: "STO", floor: "first", icon: "clipboard-outline" },
  { id: "second-mock-up", name: "Mock Up", floor: "second", icon: "construct-outline" },
  { id: "second-classroom-1", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-2", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-3", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-4", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-5", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-6", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-7", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-8", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-laboratory", name: "Laboratory", floor: "second", icon: "flask-outline" },
  { id: "second-tesda", name: "TESDA", floor: "second", icon: "ribbon-outline" },
  { id: "second-hallway", name: "Hallway", floor: "second", icon: "git-branch-outline" },
  { id: "second-female-cr", name: "Female CR", floor: "second", icon: "woman-outline" },
  { id: "second-male-cr", name: "Male CR", floor: "second", icon: "man-outline" },
  { id: "second-fire-exit-left", name: "Fire Exit", floor: "second", icon: "exit-outline" },
  { id: "second-fire-exit-center", name: "Fire Exit", floor: "second", icon: "exit-outline" },
  { id: "second-fire-exit-right", name: "Fire Exit", floor: "second", icon: "exit-outline" },
  { id: "third-workshop", name: "Workshop", floor: "third", icon: "hammer-outline" },
  { id: "third-tools-room", name: "Tools Room", floor: "third", icon: "build-outline" },
  { id: "third-classroom-1", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-2", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-3", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-4", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-5", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-library", name: "Library", floor: "third", icon: "library-outline" },
  { id: "third-students-lounge", name: "Students Lounge", floor: "third", icon: "cafe-outline" },
  { id: "third-female-cr", name: "Female CR", floor: "third", icon: "woman-outline" },
  { id: "third-male-cr", name: "Male CR", floor: "third", icon: "man-outline" },
  { id: "third-fire-exit", name: "Fire Exit", floor: "third", icon: "exit-outline" },
];

export const MONITORING_MAP_BLUEPRINTS = {
  ground: GROUND_FLOOR_BLUEPRINT,
  first: MEZZANINE_BLUEPRINT,
  mezzanine: MEZZANINE_BLUEPRINT,
  second: SECOND_FLOOR_BLUEPRINT,
  third: THIRD_FLOOR_BLUEPRINT,
};

// Text overlays for the new blueprint images. Rename or reposition rooms here.
export const MONITORING_MAP_LABELS = {
  ground: [
    { id: "ground-lobby", text: "Lobby", x: 8, y: 34, width: 8 },
    { id: "ground-cashier", text: "Cashier", x: 15.8, y: 20, width: 6 },
    { id: "ground-up", text: "UP", x: 24.8, y: 19, width: 4 },
    { id: "ground-file-room", text: "File Room", x: 33.5, y: 19, width: 9 },
    { id: "ground-staff", text: "Staff", x: 15.7, y: 44, width: 6 },
    { id: "ground-accounting", text: "Acct'G", x: 22.8, y: 44, width: 6 },
    { id: "ground-registrar", text: "Register", x: 28.4, y: 44, width: 6 },
    { id: "ground-storage-main", text: "Storage", x: 36, y: 44, width: 7 },
    { id: "ground-storage-small", text: "Storage", x: 41.1, y: 43.5, width: 5 },
    { id: "ground-offices", text: "Offices", x: 60.8, y: 35.5, width: 10 },
    { id: "ground-pwd-cr", text: "PWD CR", x: 78.6, y: 32.5, width: 6 },
    { id: "ground-he-she", text: "HE, SHE", x: 78.9, y: 41.8, width: 6 },
    { id: "ground-kitchen", text: "Kitchen", x: 88.4, y: 24, width: 7 },
    { id: "ground-fire-exit", text: "Fire Exit", x: 88.2, y: 45.8, width: 8 },
  ],
  first: [
    { id: "conference-room", text: "Conference Room", x: 8.4, y: 36.5, width: 13 },
    { id: "chairman", text: "Chairman", x: 19, y: 42, width: 8 },
    { id: "flight-operations", text: "Flight Operations", x: 30, y: 47, width: 12 },
    { id: "head-of-training-room", text: "Head Of Training\nRoom", x: 43.2, y: 42, width: 12 },
    { id: "it-room", text: "I.T Room", x: 56, y: 46, width: 9 },
    { id: "faculty-room", text: "Faculty Room", x: 70, y: 38, width: 11 },
    { id: "academy-director", text: "Academy Director", x: 83.3, y: 38.8, width: 12 },
    { id: "mezzanine-fire-exit", text: "Fire Exit", x: 88.8, y: 20, width: 8 },
    { id: "mezzanine-cr", text: "CR", x: 97.5, y: 24.5, width: 4 },
    { id: "sto", text: "STO", x: 96.8, y: 47, width: 4 },
  ],
  mezzanine: [
    { id: "conference-room", text: "Conference Room", x: 8.4, y: 36.5, width: 13 },
    { id: "chairman", text: "Chairman", x: 19, y: 42, width: 8 },
    { id: "flight-operations", text: "Flight Operations", x: 30, y: 47, width: 12 },
    { id: "head-of-training-room", text: "Head Of Training\nRoom", x: 43.2, y: 42, width: 12 },
    { id: "it-room", text: "I.T Room", x: 56, y: 46, width: 9 },
    { id: "faculty-room", text: "Faculty Room", x: 70, y: 38, width: 11 },
    { id: "academy-director", text: "Academy Director", x: 83.3, y: 38.8, width: 12 },
    { id: "mezzanine-fire-exit", text: "Fire Exit", x: 88.8, y: 20, width: 8 },
    { id: "mezzanine-cr", text: "CR", x: 97.5, y: 24.5, width: 4 },
    { id: "sto", text: "STO", x: 96.8, y: 47, width: 4 },
  ],
  second: [
    { id: "second-classroom-top-left", text: "Classroom", x: 8.8, y: 24, width: 10 },
    { id: "second-fire-exit-left", text: "Fire Exit", x: 15.6, y: 22, width: 8 },
    { id: "second-mock-up", text: "Mock Up", x: 8.6, y: 53, width: 9 },
    { id: "second-classroom-bottom-left", text: "Classroom", x: 8.7, y: 81.5, width: 10 },
    { id: "second-classroom-1", text: "Classroom", x: 27, y: 42, width: 10 },
    { id: "second-classroom-2", text: "Classroom", x: 27, y: 82, width: 10 },
    { id: "second-classroom-3", text: "Classroom", x: 42, y: 42, width: 10 },
    { id: "second-classroom-4", text: "Classroom", x: 42, y: 82, width: 10 },
    { id: "second-fire-exit-center", text: "Fire Exit", x: 48, y: 22, width: 8 },
    { id: "second-hallway", text: "Hallway", x: 47.5, y: 61, width: 10, size: 18 },
    { id: "second-classroom-5", text: "Classroom", x: 56.5, y: 42, width: 10 },
    { id: "second-classroom-6", text: "Classroom", x: 56.5, y: 82, width: 10 },
    { id: "second-laboratory", text: "Laboratory", x: 71, y: 42, width: 10 },
    { id: "second-classroom-7", text: "Classroom", x: 71, y: 82, width: 10 },
    { id: "second-fire-exit-right", text: "Fire Exit", x: 78.5, y: 22, width: 8 },
    { id: "second-tesda", text: "TESDA", x: 91, y: 22.5, width: 7 },
    { id: "second-female-cr", text: "Female CR", x: 88.5, y: 44, width: 8 },
    { id: "second-male-cr", text: "Male CR", x: 88.5, y: 56, width: 8 },
  ],
  third: [
    { id: "third-workshop", text: "Workshop", x: 8.2, y: 38.5, width: 10 },
    { id: "third-classroom-1", text: "Classroom", x: 25.4, y: 38.5, width: 10 },
    { id: "third-classroom-2", text: "Classroom", x: 40.3, y: 38.5, width: 10 },
    { id: "third-classroom-3", text: "Classroom", x: 55.2, y: 38.5, width: 10 },
    { id: "third-library", text: "Library", x: 70.2, y: 38.5, width: 8 },
    { id: "third-classroom-4", text: "Classroom", x: 25.8, y: 79, width: 10 },
    { id: "third-classroom-5", text: "Classroom", x: 41.4, y: 79, width: 10 },
    { id: "third-students-lounge", text: "Students Lounge", x: 64, y: 75, width: 15 },
    { id: "third-tools-room", text: "Tools Room", x: 5.8, y: 88.5, width: 8 },
    { id: "third-female-cr", text: "Female CR", x: 90.8, y: 38, width: 8 },
    { id: "third-male-cr", text: "Male CR", x: 91, y: 52, width: 8 },
    { id: "third-fire-exit", text: "Fire Exit", x: 49, y: 15, width: 8 },
  ],
};

export const MONITORING_MAP_OFFICE_POSITIONS = {
  "ground-lobby": { x: 10, y: 32 },
  "ground-cashier": { x: 18, y: 22 },
  "ground-staff": { x: 18, y: 43 },
  "ground-accounting": { x: 24, y: 43 },
  "ground-registrar": { x: 29, y: 43 },
  "ground-file-room": { x: 35, y: 22 },
  "ground-storage-main": { x: 36, y: 43 },
  "ground-storage-small": { x: 40, y: 43 },
  "ground-offices": { x: 59, y: 37 },
  "ground-pwd-cr": { x: 77, y: 35 },
  "ground-he-she": { x: 77, y: 43 },
  "ground-kitchen": { x: 83, y: 24 },
  "ground-fire-exit": { x: 84, y: 43 },
  "conference-room": { x: 10, y: 36 },
  chairman: { x: 21, y: 40 },
  "flight-operations": { x: 33, y: 43 },
  "head-of-training-room": { x: 45, y: 42 },
  "it-room": { x: 57, y: 42 },
  "faculty-room": { x: 69, y: 36 },
  "academy-director": { x: 82, y: 37 },
  "mezzanine-cr": { x: 94, y: 25 },
  sto: { x: 94, y: 44 },
  "second-mock-up": { x: 10, y: 46 },
  "second-classroom-1": { x: 10, y: 67 },
  "second-classroom-2": { x: 27, y: 36 },
  "second-classroom-3": { x: 27, y: 68 },
  "second-classroom-4": { x: 41, y: 36 },
  "second-classroom-5": { x: 41, y: 68 },
  "second-classroom-6": { x: 56, y: 36 },
  "second-classroom-7": { x: 56, y: 68 },
  "second-classroom-8": { x: 70, y: 68 },
  "second-laboratory": { x: 70, y: 36 },
  "second-tesda": { x: 86, y: 20 },
  "second-hallway": { x: 48, y: 53 },
  "second-female-cr": { x: 86, y: 36 },
  "second-male-cr": { x: 86, y: 47 },
  "second-fire-exit-left": { x: 16, y: 20 },
  "second-fire-exit-center": { x: 47, y: 20 },
  "second-fire-exit-right": { x: 76, y: 20 },
  "third-workshop": { x: 11, y: 48 },
  "third-tools-room": { x: 7, y: 82 },
  "third-classroom-1": { x: 25, y: 48 },
  "third-classroom-2": { x: 39, y: 48 },
  "third-classroom-3": { x: 53, y: 48 },
  "third-classroom-4": { x: 25, y: 76 },
  "third-classroom-5": { x: 39, y: 76 },
  "third-library": { x: 67, y: 48 },
  "third-students-lounge": { x: 60, y: 76 },
  "third-female-cr": { x: 84, y: 49 },
  "third-male-cr": { x: 84, y: 61 },
  "third-fire-exit": { x: 47, y: 31 },
};
