const GROUND_FLOOR_BLUEPRINT = require("../assets/maps/GroundFloor3.png");
const MEZZANINE_BLUEPRINT = require("../assets/maps/Mezzanine3.png");
const SECOND_FLOOR_BLUEPRINT = require("../assets/maps/SecondFloor3.png");
const THIRD_FLOOR_BLUEPRINT = require("../assets/maps/ThirdFloor3.png");

export const MONITORING_MAP_FLOORS = [
  { id: "ground", name: "Ground Floor", icon: "home-outline" },
  { id: "first", name: "Mezzanine", icon: "arrow-up-outline" },
  { id: "second", name: "Second Floor", icon: "layers-outline" },
  { id: "third", name: "Third Floor", icon: "layers-outline" },
];

export const MONITORING_MAP_OFFICES = [
  { id: "ground-lobby", name: "Lobby", floor: "ground", icon: "home-outline" },
  { id: "ground-cashier", name: "Cashier", floor: "ground", icon: "cash-outline" },
  { id: "ground-staff", name: "Staff", floor: "ground", icon: "people-outline" },
  { id: "ground-accounting", name: "Accounting", floor: "ground", icon: "calculator-outline" },
  { id: "ground-registrar", name: "Registrar", floor: "ground", icon: "document-text-outline" },
  { id: "ground-file-room", name: "File Room", floor: "ground", icon: "folder-open-outline" },
  { id: "ground-storage-main", name: "Storage", floor: "ground", icon: "archive-outline" },
  { id: "ground-storage-small", name: "Storage Room", floor: "ground", icon: "cube-outline" },
  { id: "ground-offices", name: "Offices", floor: "ground", icon: "business-outline" },
  { id: "ground-pwd-cr", name: "PWD CR", floor: "ground", icon: "accessibility-outline" },
  { id: "ground-he-she", name: "H.E/SHE", floor: "ground", icon: "medical-outline" },
  { id: "ground-kitchen", name: "Kitchen", floor: "ground", icon: "restaurant-outline" },
  { id: "ground-fire-exit", name: "Fire Exit", floor: "ground", icon: "exit-outline" },
  { id: "conference-room", name: "Conference Room", floor: "first", icon: "people-outline" },
  { id: "chairman", name: "Chairman", floor: "first", icon: "person-circle-outline" },
  { id: "flight-operations", name: "Flight Operations", floor: "first", icon: "airplane-outline" },
  { id: "head-of-training-room", name: "Head Of Training Room", floor: "first", icon: "school-outline" },
  { id: "it-room", name: "I.T Room", floor: "first", icon: "desktop-outline" },
  { id: "faculty-room", name: "Faculty Room", floor: "first", icon: "people-circle-outline" },
  { id: "academy-director", name: "Academy Director", floor: "first", icon: "briefcase-outline" },
  { id: "mezzanine-cr", name: "CR", floor: "first", icon: "water-outline" },
  { id: "sto", name: "STO", floor: "first", icon: "clipboard-outline" },
  { id: "second-mock-up", name: "Mock Up", floor: "second", icon: "construct-outline" },
  { id: "second-classroom-1", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-2", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-3", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-4", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-5", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-6", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-7", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-8", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-laboratory", name: "Laboratory", floor: "second", icon: "flask-outline" },
  { id: "second-tesda", name: "TESDA", floor: "second", icon: "ribbon-outline" },
  { id: "second-hallway", name: "Hallway", floor: "second", icon: "git-branch-outline" },
  { id: "second-female-cr", name: "Female CR", floor: "second", icon: "woman-outline" },
  { id: "second-male-cr", name: "Male CR", floor: "second", icon: "man-outline" },
  { id: "second-fire-exit-left", name: "Fire Exit", floor: "second", icon: "exit-outline" },
  { id: "second-fire-exit-center", name: "Fire Exit", floor: "second", icon: "exit-outline" },
  { id: "second-fire-exit-right", name: "Fire Exit", floor: "second", icon: "exit-outline" },
  { id: "third-workshop", name: "Workshop", floor: "third", icon: "hammer-outline" },
  { id: "third-tools-room", name: "Tools Room", floor: "third", icon: "build-outline" },
  { id: "third-classroom-1", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-2", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-3", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-4", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-5", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-library", name: "Library", floor: "third", icon: "library-outline" },
  { id: "third-students-lounge", name: "Students Lounge", floor: "third", icon: "cafe-outline" },
  { id: "third-female-cr", name: "Female CR", floor: "third", icon: "woman-outline" },
  { id: "third-male-cr", name: "Male CR", floor: "third", icon: "man-outline" },
  { id: "third-fire-exit", name: "Fire Exit", floor: "third", icon: "exit-outline" },
];

export const MONITORING_MAP_BLUEPRINTS = {
  ground: GROUND_FLOOR_BLUEPRINT,
  first: MEZZANINE_BLUEPRINT,
  mezzanine: MEZZANINE_BLUEPRINT,
  second: SECOND_FLOOR_BLUEPRINT,
  third: THIRD_FLOOR_BLUEPRINT,
};

// Text overlays for the active Floor3 blueprint images. Rename or reposition rooms here.
export const MONITORING_MAP_LABELS = {
  ground: [
    { id: "ground-lobby", text: "Lobby", x: 6.8, y: 40, width: 8 },
    { id: "ground-cashier", text: "Cashier", x: 15.2, y: 28.5, width: 6 },
    { id: "ground-up", text: "UP", x: 24.3, y: 28, width: 4 },
    { id: "ground-file-room", text: "File Room", x: 32.4, y: 28.5, width: 9 },
    { id: "ground-staff", text: "Staff", x: 15.2, y: 46.8, width: 6 },
    { id: "ground-accounting", text: "Acct'G", x: 21.8, y: 46.8, width: 6 },
    { id: "ground-registrar", text: "Registrar", x: 26.9, y: 46.8, width: 7 },
    { id: "ground-storage-main", text: "Storage", x: 33.1, y: 46.8, width: 7 },
    { id: "ground-storage-small", text: "Storage", x: 38.7, y: 46.8, width: 5 },
    { id: "ground-offices", text: "Offices", x: 62, y: 40, width: 10 },
    { id: "ground-pwd-cr", text: "PWD CR", x: 78.6, y: 32.5, width: 6 },
    { id: "ground-he-she", text: "HE, SHE", x: 78.9, y: 41.8, width: 6 },
    { id: "ground-kitchen", text: "Kitchen", x: 88.4, y: 33, width: 7 },
    { id: "ground-fire-exit", text: "Fire Exit", x: 88.2, y: 45.8, width: 8 },
  ],
  first: [
    { id: "conference-room", text: "Conference Room", x: 7.6, y: 41, width: 12 },
    { id: "chairman", text: "Chairman", x: 16.8, y: 45, width: 8 },
    { id: "flight-operations", text: "Flight Operations", x: 27.2, y: 47, width: 11 },
    { id: "head-of-training-room", text: "Head Of Training\nRoom", x: 36, y: 44, width: 11 },
    { id: "it-room", text: "I.T Room", x: 47, y: 45, width: 8 },
    { id: "faculty-room", text: "Faculty Room", x: 61.8, y: 38, width: 11 },
    { id: "academy-director", text: "Academy Director", x: 77.4, y: 39, width: 11 },
    { id: "mezzanine-fire-exit", text: "Fire Exit", x: 86.5, y: 22, width: 7 },
    { id: "mezzanine-cr", text: "CR", x: 86.8, y: 27.5, width: 4 },
    { id: "sto", text: "STO", x: 86.8, y: 47, width: 4 },
  ],
  mezzanine: [
    { id: "conference-room", text: "Conference Room", x: 7.6, y: 41, width: 12 },
    { id: "chairman", text: "Chairman", x: 16.8, y: 45, width: 8 },
    { id: "flight-operations", text: "Flight Operations", x: 27.2, y: 47, width: 11 },
    { id: "head-of-training-room", text: "Head Of Training\nRoom", x: 36, y: 44, width: 11 },
    { id: "it-room", text: "I.T Room", x: 47, y: 45, width: 8 },
    { id: "faculty-room", text: "Faculty Room", x: 61.8, y: 38, width: 11 },
    { id: "academy-director", text: "Academy Director", x: 77.4, y: 39, width: 11 },
    { id: "mezzanine-fire-exit", text: "Fire Exit", x: 86.5, y: 22, width: 7 },
    { id: "mezzanine-cr", text: "CR", x: 86.8, y: 27.5, width: 4 },
    { id: "sto", text: "STO", x: 86.8, y: 47, width: 4 },
  ],
  second: [
    { id: "second-classroom-top-left", text: "Classroom", x: 20.5, y: 24, width: 10 },
    { id: "second-fire-exit-left", text: "Fire Exit", x: 15.6, y: 22, width: 8 },
    { id: "second-mock-up", text: "Mock Up", x: 20.5, y: 53, width: 9 },
    { id: "second-classroom-bottom-left", text: "Classroom", x: 20.5, y: 81.5, width: 10 },
    { id: "second-classroom-1", text: "Classroom", x: 33, y: 42, width: 10 },
    { id: "second-classroom-2", text: "Classroom", x: 33, y: 82, width: 10 },
    { id: "second-classroom-3", text: "Classroom", x: 46.5, y: 42, width: 10 },
    { id: "second-classroom-4", text: "Classroom", x: 46.5, y: 82, width: 10 },
    { id: "second-fire-exit-center", text: "Fire Exit", x: 48, y: 22, width: 8 },
    { id: "second-hallway", text: "Hallway", x: 47.5, y: 61, width: 10, size: 18 },
    { id: "second-classroom-5", text: "Classroom", x: 60, y: 42, width: 10 },
    { id: "second-classroom-6", text: "Classroom", x: 60, y: 82, width: 10 },
    { id: "second-laboratory", text: "Laboratory", x: 73.5, y: 42, width: 10 },
    { id: "second-classroom-7", text: "Classroom", x: 73.5, y: 82, width: 10 },
    { id: "second-fire-exit-right", text: "Fire Exit", x: 80, y: 22, width: 8 },
    { id: "second-tesda", text: "TESDA", x: 91, y: 22.5, width: 7 },
    { id: "second-female-cr", text: "Female CR", x: 88.2, y: 44, width: 8 },
    { id: "second-male-cr", text: "Male CR", x: 88.2, y: 56, width: 8 },
  ],
  third: [
    { id: "third-workshop", text: "Workshop", x: 21.5, y: 38.5, width: 10 },
    { id: "third-classroom-1", text: "Classroom", x: 35, y: 38.5, width: 10 },
    { id: "third-classroom-2", text: "Classroom", x: 48, y: 38.5, width: 10 },
    { id: "third-classroom-3", text: "Classroom", x: 61, y: 38.5, width: 10 },
    { id: "third-library", text: "Library", x: 73.5, y: 38.5, width: 8 },
    { id: "third-classroom-4", text: "Classroom", x: 35, y: 79, width: 10 },
    { id: "third-classroom-5", text: "Classroom", x: 48, y: 79, width: 10 },
    { id: "third-students-lounge", text: "Students Lounge", x: 67, y: 75, width: 15 },
    { id: "third-tools-room", text: "Tools Room", x: 21.5, y: 88.5, width: 8 },
    { id: "third-female-cr", text: "Female CR", x: 88, y: 38, width: 8 },
    { id: "third-male-cr", text: "Male CR", x: 88, y: 52, width: 8 },
    { id: "third-fire-exit", text: "Fire Exit", x: 54.5, y: 15, width: 8 },
  ],
};

export const MONITORING_MAP_OFFICE_POSITIONS = {
  "ground-lobby": { x: 6.8, y: 40 },
  "ground-cashier": { x: 15.2, y: 28.5 },
  "ground-staff": { x: 15.2, y: 46.8 },
  "ground-accounting": { x: 21.8, y: 46.8 },
  "ground-registrar": { x: 26.9, y: 46.8 },
  "ground-file-room": { x: 32.4, y: 28.5 },
  "ground-storage-main": { x: 33.1, y: 46.8 },
  "ground-storage-small": { x: 38.7, y: 46.8 },
  "ground-offices": { x: 62, y: 40 },
  "ground-pwd-cr": { x: 78.6, y: 32.5 },
  "ground-he-she": { x: 78.9, y: 41.8 },
  "ground-kitchen": { x: 88.4, y: 33 },
  "ground-fire-exit": { x: 88.2, y: 45.8 },
  "conference-room": { x: 7.6, y: 41 },
  chairman: { x: 16.8, y: 45 },
  "flight-operations": { x: 27.2, y: 47 },
  "head-of-training-room": { x: 36, y: 44 },
  "it-room": { x: 47, y: 45 },
  "faculty-room": { x: 61.8, y: 38 },
  "academy-director": { x: 77.4, y: 39 },
  "mezzanine-cr": { x: 86.8, y: 27.5 },
  sto: { x: 86.8, y: 47 },
  "second-mock-up": { x: 20.5, y: 53 },
  "second-classroom-1": { x: 20.5, y: 81.5 },
  "second-classroom-2": { x: 33, y: 42 },
  "second-classroom-3": { x: 33, y: 82 },
  "second-classroom-4": { x: 46.5, y: 42 },
  "second-classroom-5": { x: 46.5, y: 82 },
  "second-classroom-6": { x: 60, y: 42 },
  "second-classroom-7": { x: 60, y: 82 },
  "second-classroom-8": { x: 73.5, y: 82 },
  "second-laboratory": { x: 73.5, y: 42 },
  "second-tesda": { x: 91, y: 22.5 },
  "second-hallway": { x: 47.5, y: 61 },
  "second-female-cr": { x: 88.2, y: 44 },
  "second-male-cr": { x: 88.2, y: 56 },
  "second-fire-exit-left": { x: 15.6, y: 22 },
  "second-fire-exit-center": { x: 48, y: 22 },
  "second-fire-exit-right": { x: 80, y: 22 },
  "third-workshop": { x: 21.5, y: 38.5 },
  "third-tools-room": { x: 21.5, y: 88.5 },
  "third-classroom-1": { x: 35, y: 38.5 },
  "third-classroom-2": { x: 48, y: 38.5 },
  "third-classroom-3": { x: 61, y: 38.5 },
  "third-classroom-4": { x: 35, y: 79 },
  "third-classroom-5": { x: 48, y: 79 },
  "third-library": { x: 73.5, y: 38.5 },
  "third-students-lounge": { x: 67, y: 75 },
  "third-female-cr": { x: 88, y: 38 },
  "third-male-cr": { x: 88, y: 52 },
  "third-fire-exit": { x: 54.5, y: 15 },
};
