const GROUND_FLOOR_BLUEPRINT = require("../assets/maps/GroundFloor.png");
const MEZZANINE_BLUEPRINT = require("../assets/maps/Mezzanine.png");
const SECOND_FLOOR_BLUEPRINT = require("../assets/maps/SecondFloor.png");
const THIRD_FLOOR_BLUEPRINT = require("../assets/maps/ThridFloor.png");

export const MONITORING_MAP_FLOORS = [
  { id: "ground", name: "Ground Floor", icon: "home-outline" },
  { id: "first", name: "Mezzanine", icon: "arrow-up-outline" },
  { id: "second", name: "Second Floor", icon: "layers-outline" },
  { id: "third", name: "Third Floor", icon: "layers-outline" },
];

export const MONITORING_MAP_OFFICES = [
  { id: "ground-lobby", name: "Lobby", floor: "ground", icon: "home-outline" },
  { id: "ground-cashier", name: "Cashier", floor: "ground", icon: "cash-outline" },
  { id: "ground-staff", name: "Staff", floor: "ground", icon: "people-outline" },
  { id: "ground-accounting", name: "Accounting", floor: "ground", icon: "calculator-outline" },
  { id: "ground-registrar", name: "Registrar", floor: "ground", icon: "document-text-outline" },
  { id: "ground-file-room", name: "File Room", floor: "ground", icon: "folder-open-outline" },
  { id: "ground-storage-main", name: "Storage", floor: "ground", icon: "archive-outline" },
  { id: "ground-storage-small", name: "Storage Room", floor: "ground", icon: "cube-outline" },
  { id: "ground-offices", name: "Offices", floor: "ground", icon: "business-outline" },
  { id: "ground-pwd-cr", name: "PWD CR", floor: "ground", icon: "accessibility-outline" },
  { id: "ground-he-she", name: "H.E/SHE", floor: "ground", icon: "medical-outline" },
  { id: "ground-kitchen", name: "Kitchen", floor: "ground", icon: "restaurant-outline" },
  { id: "ground-fire-exit", name: "Fire Exit", floor: "ground", icon: "exit-outline" },
  { id: "conference-room", name: "Conference Room", floor: "first", icon: "people-outline" },
  { id: "chairman", name: "Chairman", floor: "first", icon: "person-circle-outline" },
  { id: "flight-operations", name: "Flight Operations", floor: "first", icon: "airplane-outline" },
  { id: "head-of-training-room", name: "Head Of Training Room", floor: "first", icon: "school-outline" },
  { id: "it-room", name: "I.T Room", floor: "first", icon: "desktop-outline" },
  { id: "faculty-room", name: "Faculty Room", floor: "first", icon: "people-circle-outline" },
  { id: "academy-director", name: "Academy Director", floor: "first", icon: "briefcase-outline" },
  { id: "mezzanine-cr", name: "CR", floor: "first", icon: "water-outline" },
  { id: "sto", name: "STO", floor: "first", icon: "clipboard-outline" },
  { id: "second-mock-up", name: "Mock Up", floor: "second", icon: "construct-outline" },
  { id: "second-classroom-1", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-2", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-3", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-4", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-5", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-6", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-7", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-classroom-8", name: "Classroom", floor: "second", icon: "school-outline" },
  { id: "second-laboratory", name: "Laboratory", floor: "second", icon: "flask-outline" },
  { id: "second-tesda", name: "TESDA", floor: "second", icon: "ribbon-outline" },
  { id: "second-hallway", name: "Hallway", floor: "second", icon: "git-branch-outline" },
  { id: "second-female-cr", name: "Female CR", floor: "second", icon: "woman-outline" },
  { id: "second-male-cr", name: "Male CR", floor: "second", icon: "man-outline" },
  { id: "second-fire-exit-left", name: "Fire Exit", floor: "second", icon: "exit-outline" },
  { id: "second-fire-exit-center", name: "Fire Exit", floor: "second", icon: "exit-outline" },
  { id: "second-fire-exit-right", name: "Fire Exit", floor: "second", icon: "exit-outline" },
  { id: "third-workshop", name: "Workshop", floor: "third", icon: "hammer-outline" },
  { id: "third-tools-room", name: "Tools Room", floor: "third", icon: "build-outline" },
  { id: "third-classroom-1", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-2", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-3", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-4", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-classroom-5", name: "Classroom", floor: "third", icon: "school-outline" },
  { id: "third-library", name: "Library", floor: "third", icon: "library-outline" },
  { id: "third-students-lounge", name: "Students Lounge", floor: "third", icon: "cafe-outline" },
  { id: "third-female-cr", name: "Female CR", floor: "third", icon: "woman-outline" },
  { id: "third-male-cr", name: "Male CR", floor: "third", icon: "man-outline" },
  { id: "third-fire-exit", name: "Fire Exit", floor: "third", icon: "exit-outline" },
];

export const MONITORING_MAP_BLUEPRINTS = {
  ground: GROUND_FLOOR_BLUEPRINT,
  first: MEZZANINE_BLUEPRINT,
  mezzanine: MEZZANINE_BLUEPRINT,
  second: SECOND_FLOOR_BLUEPRINT,
  third: THIRD_FLOOR_BLUEPRINT,
};

export const MONITORING_MAP_OFFICE_POSITIONS = {
  "ground-lobby": { x: 10, y: 32 },
  "ground-cashier": { x: 18, y: 22 },
  "ground-staff": { x: 18, y: 43 },
  "ground-accounting": { x: 24, y: 43 },
  "ground-registrar": { x: 29, y: 43 },
  "ground-file-room": { x: 35, y: 22 },
  "ground-storage-main": { x: 36, y: 43 },
  "ground-storage-small": { x: 40, y: 43 },
  "ground-offices": { x: 59, y: 37 },
  "ground-pwd-cr": { x: 77, y: 35 },
  "ground-he-she": { x: 77, y: 43 },
  "ground-kitchen": { x: 83, y: 24 },
  "ground-fire-exit": { x: 84, y: 43 },
  "conference-room": { x: 10, y: 36 },
  chairman: { x: 21, y: 40 },
  "flight-operations": { x: 33, y: 43 },
  "head-of-training-room": { x: 45, y: 42 },
  "it-room": { x: 57, y: 42 },
  "faculty-room": { x: 69, y: 36 },
  "academy-director": { x: 82, y: 37 },
  "mezzanine-cr": { x: 94, y: 25 },
  sto: { x: 94, y: 44 },
  "second-mock-up": { x: 10, y: 46 },
  "second-classroom-1": { x: 10, y: 67 },
  "second-classroom-2": { x: 27, y: 36 },
  "second-classroom-3": { x: 27, y: 68 },
  "second-classroom-4": { x: 41, y: 36 },
  "second-classroom-5": { x: 41, y: 68 },
  "second-classroom-6": { x: 56, y: 36 },
  "second-classroom-7": { x: 56, y: 68 },
  "second-classroom-8": { x: 70, y: 68 },
  "second-laboratory": { x: 70, y: 36 },
  "second-tesda": { x: 86, y: 20 },
  "second-hallway": { x: 48, y: 53 },
  "second-female-cr": { x: 86, y: 36 },
  "second-male-cr": { x: 86, y: 47 },
  "second-fire-exit-left": { x: 16, y: 20 },
  "second-fire-exit-center": { x: 47, y: 20 },
  "second-fire-exit-right": { x: 76, y: 20 },
  "third-workshop": { x: 11, y: 48 },
  "third-tools-room": { x: 7, y: 82 },
  "third-classroom-1": { x: 25, y: 48 },
  "third-classroom-2": { x: 39, y: 48 },
  "third-classroom-3": { x: 53, y: 48 },
  "third-classroom-4": { x: 25, y: 76 },
  "third-classroom-5": { x: 39, y: 76 },
  "third-library": { x: 67, y: 48 },
  "third-students-lounge": { x: 60, y: 76 },
  "third-female-cr": { x: 84, y: 49 },
  "third-male-cr": { x: 84, y: 61 },
  "third-fire-exit": { x: 47, y: 31 },
};
