import { StyleSheet, Platform, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const isWeb = Platform.OS === "web";
const isSmallPhone = width <= 375;
const isTablet = width >= 768 && width < 1024;

const fontSizes = {
  xs: isSmallPhone ? 11 : 12,
  sm: isSmallPhone ? 12 : 14,
  base: isSmallPhone ? 14 : 16,
  lg: isSmallPhone ? 17 : 19,
  xl: isSmallPhone ? 22 : 26,
  xxl: isSmallPhone ? 28 : 34,
};

const spacing = {
  xs: isSmallPhone ? 4 : 6,
  sm: isSmallPhone ? 8 : 10,
  base: isSmallPhone ? 14 : 16,
  lg: isSmallPhone ? 18 : 22,
  xl: isSmallPhone ? 24 : 30,
  xxl: isSmallPhone ? 30 : 38,
};

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F4F8FC",
  },
  keyboardView: {
    flex: 1,
    backgroundColor: "#F4F8FC",
  },
  mainScrollView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: spacing.xxl,
  },
  formShell: {
    flex: 1,
    width: "100%",
    ...(isWeb && {
      maxWidth: 860,
      alignSelf: "center",
      paddingHorizontal: spacing.base,
    }),
  },

  header: {
    width: "100%",
    paddingTop: Platform.select({ ios: 54, android: 42, web: 46 }),
    paddingBottom: 42,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#063B34",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.16,
        shadowRadius: 18,
      },
      android: { elevation: 7 },
      web: {
        boxShadow: "0px 18px 40px rgba(6, 59, 52, 0.18)",
      },
    }),
  },
  headerButtons: {
    position: "absolute",
    top: Platform.select({ ios: 52, android: 42, web: 42 }),
    left: spacing.base,
    right: spacing.base,
    zIndex: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255,255,255,0.16)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    ...(isWeb && {
      cursor: "pointer",
      transition: "transform 0.2s ease, background-color 0.2s ease",
      ":hover": {
        backgroundColor: "rgba(255,255,255,0.24)",
        transform: "translateY(-1px)",
      },
    }),
  },
  exitButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255,255,255,0.16)",
    justifyContent: "center",
    alignItems: "center",
  },
  headerContent: {
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    width: "100%",
    maxWidth: 720,
    alignSelf: "center",
  },
  headerBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "rgba(255,255,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: spacing.lg,
    ...Platform.select({
      web: { backdropFilter: "blur(10px)" },
    }),
  },
  headerBadgeLogo: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
    marginRight: 10,
  },
  headerBadgeTextWrap: {
    justifyContent: "center",
  },
  headerBadgeEyebrow: {
    fontSize: fontSizes.xs,
    fontWeight: "700",
    color: "rgba(255,255,255,0.76)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  headerBadgeTitle: {
    fontSize: fontSizes.sm,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  headerIconContainer: {
    marginBottom: spacing.sm,
    borderRadius: 36,
    overflow: "hidden",
  },
  headerIconGradient: {
    width: 72,
    height: 72,
    borderRadius: 36,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  headerTitle: {
    fontSize: fontSizes.xxl,
    fontWeight: "800",
    color: "#FFFFFF",
    marginBottom: 6,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: fontSizes.lg,
    color: "rgba(255,255,255,0.94)",
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 8,
  },
  headerDescription: {
    fontSize: fontSizes.sm,
    color: "rgba(255,255,255,0.84)",
    textAlign: "center",
    lineHeight: 22,
    maxWidth: 540,
  },

  progressContainer: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: spacing.base,
    marginTop: -22,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.base,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E4EDF7",
    ...Platform.select({
      ios: {
        shadowColor: "#0F172A",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 10,
      },
      android: { elevation: 2 },
      web: { boxShadow: "0px 10px 20px rgba(15, 23, 42, 0.05)" },
    }),
  },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.xs,
  },
  progressTitle: {
    fontSize: fontSizes.sm,
    fontWeight: "600",
    color: "#64748B",
  },
  progressPercentage: {
    fontSize: fontSizes.sm,
    fontWeight: "700",
    color: "#047857",
  },
  progressBarContainer: {
    height: 6,
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    backgroundColor: "#059669",
    borderRadius: 999,
  },

  stepIndicatorContainer: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: spacing.base,
    marginTop: spacing.base,
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.base,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E4EDF7",
  },
  stepWrapper: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  stepCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#EFF4F8",
    justifyContent: "center",
    alignItems: "center",
  },
  stepCircleActive: {
    backgroundColor: "#059669",
  },
  stepCircleText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#94A3B8",
  },
  stepCircleTextActive: {
    color: "#FFFFFF",
  },
  stepConnector: {
    flex: 1,
    height: 3,
    backgroundColor: "#E2E8F0",
    marginHorizontal: spacing.xs,
    borderRadius: 999,
  },
  stepConnectorActive: {
    backgroundColor: "#059669",
  },
  stepLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 4,
  },
  stepLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#94A3B8",
  },
  stepLabelActive: {
    color: "#047857",
  },

  content: {
    padding: spacing.lg,
    ...(isWeb && { maxWidth: 760, alignSelf: "center", width: "100%" }),
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: spacing.lg,
    gap: spacing.base,
  },
  sectionTextBlock: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: fontSizes.xl,
    fontWeight: "800",
    color: "#0F172A",
    letterSpacing: -0.4,
    marginBottom: 4,
  },
  sectionDescription: {
    fontSize: fontSizes.sm,
    color: "#64748B",
    lineHeight: 21,
    maxWidth: 520,
  },
  sectionBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ECFDF5",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    gap: 4,
    borderWidth: 1,
    borderColor: "#CFF4E5",
  },
  sectionBadgeText: {
    fontSize: fontSizes.xs,
    fontWeight: "700",
    color: "#047857",
  },
  formGrid: {
    gap: spacing.base,
    marginBottom: spacing.xl,
  },

  stepInsightCard: {
    backgroundColor: "#F7FFFA",
    borderWidth: 1,
    borderColor: "#CDEEDF",
    borderRadius: 22,
    padding: spacing.base,
    marginBottom: spacing.base,
    ...Platform.select({
      ios: {
        shadowColor: "#047857",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
      },
      android: { elevation: 1 },
      web: { boxShadow: "0px 10px 22px rgba(5, 150, 105, 0.06)" },
    }),
  },
  stepInsightHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  stepInsightIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#DDF8EA",
    alignItems: "center",
    justifyContent: "center",
  },
  stepInsightTextWrap: {
    flex: 1,
  },
  stepInsightTitle: {
    fontSize: fontSizes.base,
    fontWeight: "800",
    color: "#065F46",
    marginBottom: 4,
  },
  stepInsightSubtitle: {
    fontSize: fontSizes.sm,
    color: "#4B5563",
    lineHeight: 20,
  },
  stepInsightStats: {
    flexDirection: "row",
    alignItems: "stretch",
    marginTop: spacing.base,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2EAF2",
    overflow: "hidden",
  },
  stepInsightStat: {
    flex: 1,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.xs,
    alignItems: "center",
    justifyContent: "center",
  },
  stepInsightStatValue: {
    fontSize: fontSizes.base,
    fontWeight: "800",
    color: "#0F172A",
  },
  stepInsightStatLabel: {
    fontSize: fontSizes.xs,
    color: "#64748B",
    marginTop: 3,
    textAlign: "center",
  },
  stepInsightDivider: {
    width: 1,
    backgroundColor: "#E2E8F0",
  },
  reviewChecklist: {
    marginTop: spacing.base,
    gap: spacing.sm,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2EAF2",
    padding: spacing.base,
  },
  reviewChecklistItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  reviewChecklistText: {
    flex: 1,
    fontSize: fontSizes.sm,
    color: "#334155",
    fontWeight: "600",
  },

  idUploadSection: {
    marginBottom: spacing.base,
  },
  idCardContainer: {
    marginBottom: spacing.sm,
  },
  idCardTitle: {
    fontSize: fontSizes.base,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 4,
  },
  idCardSubtitle: {
    fontSize: fontSizes.sm,
    color: "#64748B",
    lineHeight: 20,
  },

  formCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    padding: spacing.base,
    borderWidth: 1,
    borderColor: "#E4EDF7",
    ...Platform.select({
      ios: {
        shadowColor: "#0F172A",
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.04,
        shadowRadius: 12,
      },
      android: { elevation: 1 },
      web: { boxShadow: "0px 10px 22px rgba(15, 23, 42, 0.04)" },
    }),
  },
  formCardFocused: {
    borderColor: "#059669",
    borderWidth: 2,
  },
  formCardError: {
    borderColor: "#FECACA",
    backgroundColor: "#FFF8F8",
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  cardIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.xs,
  },
  cardLabel: {
    fontSize: fontSizes.base,
    fontWeight: "700",
    color: "#0F172A",
    flex: 1,
  },
  cardLabelSmall: {
    fontSize: fontSizes.sm,
    fontWeight: "700",
    color: "#0F172A",
    flex: 1,
  },
  requiredBadge: {
    fontSize: 10,
    fontWeight: "700",
    color: "#DC2626",
    backgroundColor: "#FEF2F2",
    paddingHorizontal: spacing.xs,
    paddingVertical: 3,
    borderRadius: 999,
  },
  optionalBadge: {
    fontSize: 10,
    fontWeight: "600",
    color: "#64748B",
    backgroundColor: "#F1F5F9",
    paddingHorizontal: spacing.xs,
    paddingVertical: 3,
    borderRadius: 999,
  },

  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FBFE",
    borderWidth: 1,
    borderColor: "#E2EAF2",
    borderRadius: 16,
    paddingHorizontal: spacing.base,
    minHeight: 52,
    gap: spacing.xs,
  },
  inputContainerFocused: {
    borderColor: "#059669",
    borderWidth: 2,
    backgroundColor: "#FFFFFF",
  },
  inputContainerError: {
    borderColor: "#EF4444",
    backgroundColor: "#FEF2F2",
  },
  input: {
    flex: 1,
    fontSize: fontSizes.base,
    color: "#0F172A",
    paddingVertical: 12,
  },
  errorText: {
    fontSize: fontSizes.xs,
    color: "#DC2626",
    marginTop: 6,
    marginLeft: spacing.xs,
    fontWeight: "600",
  },
  inputHint: {
    fontSize: fontSizes.xs,
    color: "#64748B",
    marginTop: 4,
  },

  uploadArea: {
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#F8FBFE",
    borderWidth: 2,
    borderColor: "#DCE8E2",
    borderStyle: "dashed",
    minHeight: 176,
    ...(isWeb && {
      cursor: "pointer",
      transition: "border-color 0.2s ease, background-color 0.2s ease",
      ":hover": {
        borderColor: "#059669",
        backgroundColor: "#ECFDF5",
      },
    }),
  },
  uploadAreaError: {
    borderColor: "#EF4444",
    backgroundColor: "#FEF2F2",
  },
  uploadPlaceholder: {
    padding: spacing.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  uploadIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#ECFDF5",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  uploadTitle: {
    fontSize: fontSizes.base,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 4,
  },
  uploadSubtitle: {
    fontSize: fontSizes.xs,
    color: "#64748B",
    textAlign: "center",
    lineHeight: 18,
  },
  uploadPreview: {
    width: "100%",
    height: 176,
    position: "relative",
  },
  previewImage: {
    width: "100%",
    height: "100%",
  },
  uploadOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  uploadGradient: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  changePhotoText: {
    color: "#FFFFFF",
    fontSize: fontSizes.sm,
    fontWeight: "700",
    marginTop: 6,
  },

  scanButton: {
    borderRadius: 16,
    overflow: "hidden",
    marginTop: spacing.sm,
    ...(isWeb && {
      transition: "transform 0.2s ease",
      ":hover": {
        transform: "translateY(-1px)",
      },
    }),
  },
  scanGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
    gap: spacing.xs,
  },
  scanButtonText: {
    color: "#FFFFFF",
    fontSize: fontSizes.sm,
    fontWeight: "700",
  },
  scanningContainer: {
    backgroundColor: "#F8FBFE",
    borderRadius: 16,
    padding: spacing.base,
    marginTop: spacing.sm,
    alignItems: "center",
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: "#DCE8E2",
  },
  scanningText: {
    fontSize: fontSizes.sm,
    color: "#047857",
    fontWeight: "600",
  },
  scanProgressContainer: {
    width: "100%",
    height: 5,
    backgroundColor: "#E2E8F0",
    borderRadius: 999,
    overflow: "hidden",
  },
  scanProgressBar: {
    height: "100%",
    backgroundColor: "#059669",
    borderRadius: 999,
  },

  dropdownButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F8FBFE",
    borderWidth: 1,
    borderColor: "#E2EAF2",
    borderRadius: 16,
    paddingHorizontal: spacing.base,
    paddingVertical: 15,
    minHeight: 52,
    ...(isWeb && {
      cursor: "pointer",
      transition: "border-color 0.2s ease, background-color 0.2s ease",
      ":hover": {
        borderColor: "#059669",
        backgroundColor: "#ECFDF5",
      },
    }),
  },
  dropdownButtonText: {
    fontSize: fontSizes.base,
    color: "#0F172A",
    flex: 1,
  },
  dropdownButtonContent: {
    flex: 1,
    marginRight: spacing.sm,
  },
  dropdownButtonMeta: {
    marginTop: 3,
    fontSize: fontSizes.xs,
    color: "#64748B",
    fontWeight: "600",
  },
  dropdownButtonPlaceholder: {
    color: "#94A3B8",
  },

  pickerModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(2, 24, 20, 0.5)",
    justifyContent: "flex-end",
    ...(isWeb && { justifyContent: "center" }),
  },
  pickerModalContainer: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    maxHeight: "80%",
    ...(isWeb && {
      borderRadius: 26,
      maxWidth: 420,
      alignSelf: "center",
      width: "90%",
      boxShadow: "0px 16px 34px rgba(15, 23, 42, 0.12)",
    }),
  },
  pickerModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
  },
  pickerModalTitle: {
    fontSize: fontSizes.lg,
    fontWeight: "700",
    color: "#0F172A",
  },
  pickerModalOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: spacing.base,
    paddingHorizontal: spacing.lg,
  },
  pickerModalOptionActive: {
    backgroundColor: "#ECFDF5",
  },
  pickerModalOptionText: {
    fontSize: fontSizes.base,
    color: "#0F172A",
  },
  pickerModalOptionContent: {
    flex: 1,
    marginRight: spacing.sm,
  },
  pickerModalOptionMeta: {
    marginTop: 3,
    fontSize: fontSizes.xs,
    color: "#64748B",
    fontWeight: "600",
  },
  pickerModalOptionTextActive: {
    color: "#059669",
    fontWeight: "700",
  },

  formRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  halfCard: {
    flex: 1,
    marginHorizontal: 0,
    padding: spacing.sm,
  },
  datePickerButtonCompact: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FBFE",
    borderWidth: 1,
    borderColor: "#E2EAF2",
    borderRadius: 14,
    paddingHorizontal: spacing.sm,
    height: 42,
    marginTop: 2,
    gap: 6,
    ...(isWeb && {
      cursor: "pointer",
      transition: "border-color 0.2s ease, background-color 0.2s ease",
      ":hover": {
        borderColor: "#059669",
        backgroundColor: "#ECFDF5",
      },
    }),
  },
  datePickerTextCompact: {
    fontSize: fontSizes.sm,
    color: "#0F172A",
    flex: 1,
    fontWeight: "600",
  },
  webDateInputCompact: {
    width: "100%",
    padding: 10,
    borderRadius: 14,
    border: "1px solid #E2EAF2",
    fontSize: fontSizes.sm,
    color: "#0F172A",
    backgroundColor: "#F8FBFE",
    marginTop: 2,
    fontFamily: "inherit",
  },
  webTimeInputCompact: {
    width: "100%",
    padding: 10,
    borderRadius: 14,
    border: "1px solid #E2EAF2",
    fontSize: fontSizes.sm,
    color: "#0F172A",
    backgroundColor: "#F8FBFE",
    marginTop: 2,
    fontFamily: "inherit",
  },

  reviewCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    padding: spacing.base,
    marginBottom: spacing.base,
    borderWidth: 1,
    borderColor: "#E4EDF7",
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.sm,
    paddingBottom: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    gap: spacing.xs,
  },
  reviewHeaderText: {
    fontSize: fontSizes.base,
    fontWeight: "700",
    color: "#0F172A",
    flex: 1,
  },
  reviewItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: spacing.xs,
    gap: spacing.sm,
  },
  reviewLabel: {
    fontSize: fontSizes.sm,
    color: "#64748B",
    flex: 1,
  },
  reviewValue: {
    fontSize: fontSizes.sm,
    color: "#0F172A",
    fontWeight: "600",
    flex: 1,
    textAlign: "right",
  },
  reviewImage: {
    width: "100%",
    height: 132,
    borderRadius: 14,
    marginTop: spacing.xs,
  },

  editButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ECFDF5",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    gap: 4,
    ...(isWeb && {
      cursor: "pointer",
      transition: "background-color 0.2s ease, transform 0.2s ease",
      ":hover": {
        backgroundColor: "#D1FAE5",
        transform: "translateY(-1px)",
      },
    }),
  },
  editButtonText: {
    fontSize: fontSizes.xs,
    fontWeight: "700",
    color: "#059669",
  },

  continueButton: {
    flex: 1.35,
    borderRadius: 18,
    overflow: "hidden",
    marginBottom: spacing.base,
    ...(isWeb && {
      cursor: "pointer",
      transition: "transform 0.2s ease, box-shadow 0.2s ease",
      ":hover": {
        transform: "translateY(-2px)",
        boxShadow: "0px 10px 24px rgba(5, 150, 105, 0.28)",
      },
    }),
  },
  gradientButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 17,
    gap: spacing.xs,
  },
  continueButtonText: {
    color: "#FFFFFF",
    fontSize: fontSizes.base,
    fontWeight: "700",
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: spacing.sm,
  },
  secondaryActionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D6E0EA",
    backgroundColor: "#FFFFFF",
    paddingVertical: 16,
    paddingHorizontal: spacing.sm,
    marginBottom: spacing.base,
    ...Platform.select({
      web: {
        cursor: "pointer",
        transition: "transform 0.2s ease, background-color 0.2s ease",
        ":hover": {
          backgroundColor: "#F8FAFC",
          transform: "translateY(-1px)",
        },
      },
    }),
  },
  secondaryActionText: {
    fontSize: fontSizes.sm,
    fontWeight: "700",
    color: "#475569",
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(2, 24, 20, 0.45)",
    justifyContent: "center",
    alignItems: "center",
    padding: spacing.lg,
  },
  privacyModalContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    width: "90%",
    maxWidth: 520,
    maxHeight: "82%",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E4EDF7",
  },
  privacyModalHeader: {
    padding: spacing.lg,
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E2E8F0",
    backgroundColor: "#F8FBFE",
  },
  privacyIconContainer: {
    marginBottom: spacing.sm,
    borderRadius: 30,
    overflow: "hidden",
  },
  privacyIconGradient: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
  },
  privacyModalTitle: {
    fontSize: fontSizes.xl,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 4,
  },
  privacyModalSubtitle: {
    fontSize: fontSizes.sm,
    color: "#64748B",
    textAlign: "center",
  },
  privacyModalContent: {
    padding: spacing.lg,
    maxHeight: 400,
  },
  privacySection: {
    marginBottom: spacing.lg,
  },
  privacySectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.xs,
    gap: spacing.xs,
  },
  privacySectionTitle: {
    fontSize: fontSizes.base,
    fontWeight: "700",
    color: "#0F172A",
  },
  privacySectionText: {
    fontSize: fontSizes.sm,
    color: "#475569",
    lineHeight: 22,
    marginBottom: 2,
    paddingLeft: 28,
  },
  privacyCheckboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    backgroundColor: "#F8FBFE",
  },
  privacyCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#059669",
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.sm,
    backgroundColor: "#FFFFFF",
  },
  privacyCheckboxChecked: {
    backgroundColor: "#059669",
  },
  privacyCheckboxText: {
    fontSize: fontSizes.sm,
    color: "#475569",
    flex: 1,
  },
  privacyLinkText: {
    color: "#059669",
    fontWeight: "700",
  },
  privacyModalActions: {
    flexDirection: "row",
    padding: spacing.base,
    gap: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  privacyDeclineButton: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: 14,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
  },
  privacyDeclineText: {
    fontSize: fontSizes.base,
    fontWeight: "700",
    color: "#64748B",
  },
  privacyAcceptButton: {
    flex: 2,
    borderRadius: 14,
    overflow: "hidden",
  },
  privacyAcceptButtonDisabled: {
    opacity: 0.6,
  },
  privacyAcceptGradient: {
    paddingVertical: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
  },
  privacyAcceptText: {
    fontSize: fontSizes.base,
    fontWeight: "700",
    color: "#FFFFFF",
  },

  successModalContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: spacing.xl,
    alignItems: "center",
    width: "90%",
    maxWidth: 420,
    borderWidth: 1,
    borderColor: "#E4EDF7",
  },
  successIconContainer: {
    marginBottom: spacing.base,
    borderRadius: 50,
    overflow: "hidden",
  },
  successIconGradient: {
    width: 84,
    height: 84,
    borderRadius: 42,
    justifyContent: "center",
    alignItems: "center",
  },
  successTitle: {
    fontSize: fontSizes.xl,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: spacing.sm,
    textAlign: "center",
  },
  successMessage: {
    fontSize: fontSizes.sm,
    color: "#64748B",
    textAlign: "center",
    marginBottom: spacing.lg,
    lineHeight: 22,
  },
  credentialsBox: {
    backgroundColor: "#F8FBFE",
    borderRadius: 18,
    padding: spacing.base,
    marginBottom: spacing.base,
    width: "100%",
    borderWidth: 1,
    borderColor: "#E2EAF2",
  },
  credentialsTitle: {
    fontSize: fontSizes.base,
    fontWeight: "700",
    color: "#059669",
  },
  credentialsTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  credentialsInfo: {
    fontSize: fontSizes.sm,
    color: "#64748B",
    marginBottom: spacing.sm,
  },
  credentialRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    marginTop: spacing.xs,
    gap: spacing.xs,
  },
  credentialLabel: {
    fontSize: fontSizes.sm,
    fontWeight: "600",
    color: "#475569",
    width: 72,
  },
  credentialValue: {
    fontSize: fontSizes.sm,
    color: "#0F172A",
    fontWeight: "600",
    flex: 1,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  copyButton: {
    padding: spacing.xs,
    borderRadius: 10,
    backgroundColor: "#ECFDF5",
  },
  successButton: {
    borderRadius: 16,
    overflow: "hidden",
    width: "100%",
  },
  successGradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    gap: spacing.xs,
  },
  successButtonText: {
    color: "#FFFFFF",
    fontSize: fontSizes.base,
    fontWeight: "700",
  },
});
